//=========================================================
// src/uart0_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8LB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "STDIO.H"
#include "stdint.h"
#include "serial.h"
// $[Generated Includes]
// [Generated Includes]$
char r;
sbit led=P1^3;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
  WDTCN=0XDE;
  WDTCN=0XAD;
}
void enable_crossbar(){
  XBR2 |= XBR2_XBARE__ENABLED;
  XBR0 |= XBR0_URT0E__ENABLED;

  P0MDOUT = P0MDOUT_B4__PUSH_PULL | P0MDOUT_B5__PUSH_PULL;
  P1MDOUT |=P1MDOUT_B3__PUSH_PULL;
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
 // enter_DefaultMode_from_RESET ();
  CLKSEL= CLKSEL_CLKDIV__SYSCLK_DIV_1 | CLKSEL_CLKSL__HFOSC0; //24.5MHz
  CKCON0 |= CKCON0_T1M__SYSCLK;
  TMOD |= TMOD_T1M__MODE2;
  enable_crossbar();
  uart_timer();
  while (1)
    {
       r=receive_char();
       if (r=='1'){
           led=0;
       }
       else if (r=='0'){
           led=1;
       }

// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
