//=========================================================
// src/myProject_7_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8LB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$
unsigned long i,j;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}
void
delay (unsigned long ms)
{
  ms=ms*326495;

  for (i = 1; i<=ms; i++)
    {
    }

}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  CLKSEL = CLKSEL_CLKDIV__SYSCLK_DIV_1 ;
  CLKSEL= CLKSEL_CLKSL__HFOSC0;
  XBR2 |= 0X40;

  P1MDOUT |=P1MDOUT_B3__PUSH_PULL;
  P1MDOUT |=P1MDOUT_B3__OPEN_DRAIN;
  while (1)
    {
      P1_B3 = 0;
      delay (1);
      P1_B3 = 1;
      delay (1);
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
