//=========================================================
// src/Interrupt_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8LB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "delay.h"
// $[Generated Includes]
// [Generated Includes]$
sbit led=P1^3;
sbit led1=P1^4;
unsigned int i =0;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
  WDTCN = 0XDE;
  WDTCN = 0XAD;
}
SI_INTERRUPT(INT0_ISR, INT0_IRQn){

  led=~led;
  for(i=0;i<=10;i++){

  }
  TCON_IE0=0;
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  XBR2 |= XBR2_XBARE__ENABLED;
  IE_EA=1;
  IE_EX0=1;
  IT01CF=IT01CF_IN0PL__ACTIVE_LOW | IT01CF_IN0SL__P0_0;
  P1MDOUT |=P1MDOUT_B3__PUSH_PULL;
  P1MDOUT |=P1MDOUT_B4__PUSH_PULL;
  while (1)
    {
      led1=0;
      delay_ms(1000);
      led1=1;
      delay_ms(1000);
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
