//=========================================================
// src/Interrupt_ET_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8LB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "serial.h"
#include "STDIO.H"
// $[Generated Includes]
// [Generated Includes]$
uint32_t volatile msTick=0;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
  WDTCN=0XDE;
  WDTCN=0XAD;

}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
void crossbar_enable(){
  CLKSEL= CLKSEL_CLKDIV__SYSCLK_DIV_1 | CLKSEL_CLKSL__HFOSC0;
  XBR2 |=XBR2_XBARE__ENABLED;
  XBR0 |=XBR0_URT0E__ENABLED;
  P0SKIP=0XCF; //  0B1100 1111
  P1SKIP=0X07;      //0B0000 0111
  XBR1 |=XBR1_PCA0ME__CEX0;
  P1MDOUT |=P1MDOUT_B3__PUSH_PULL;
  P0MDOUT |=P0MDOUT_B4__PUSH_PULL;
}
void timer_enable(){
  CKCON0= CKCON0_SCA__SYSCLK_DIV_4 | CKCON0_T0M__PRESCALE; // 24.5Mhz divide by 4=6.125Mhz
  TMOD =TMOD_T0M__MODE1;
  // 10ms->100Hz ->TH0:TL0=65536-6.125MHz/100=4286->10BE
  TH0=0X10;
  TL0=0XBE;

  IE_EA=1;
  IE_ET0=1;

  TCON_TR0=1;
}
void pwm_init(){
  PCA0CPM0 |=PCA0CPM0_PWM__ENABLED;

  PCA0CPH0=0;

  PCA0CN0 |=PCA0CN0_CR__RUN;
}

SI_INTERRUPT(TIMER0_ISR, TIMER0_IRQn){
  msTick+=10;
  TH0=0X10;
  TL0=0XBE;

  TCON_TF0=0;
}
uint32_t t0_last,t1_last;

uint16_t dt0=10;
uint16_t dt1=100;

uint8_t pwm_val=0;

int8_t pwm_dir=10;
int value=10;
char msg[64];
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  crossbar_enable();
  timer_enable();
  pwm_init();
  Uart_timer();
  while (1)
    {
      if(msTick-t0_last>=dt0){
          t0_last=msTick;
          if(pwm_val==0){
              pwm_dir=10;
          }else if(pwm_val==255){
              pwm_dir=-10;
          }
          pwm_val +=pwm_dir;

          PCA0CPH0=pwm_val;
      }
      if( msTick-t1_last>=dt1){
          t1_last=msTick;
          sprintf(msg,"value=%d \n",value);
          put_string(msg);
      }
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
